services:
  - type: web
    name: whatsapp-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_VERSION
        value: "18"