services:
  - type: web
    name: whatsapp-bot
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
    branch: main